credentials:
  usernames:
    linagora:
      email: aneugeabuer@linagora.com
      name: Linagora
      password: abc # To be replaced with hashed password
      logged_in : True
      failed_login_attempts : False
cookie:
  expiry_days: 15
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - aneugeabuer@linagora.com
