
defaults : 
  - _self_
  - llm_api : linagora
  - credentials : user1
  - architectures : macM1

senators_file_path : services/senateurs_name_last.txt

language : fr
max_tokens : 2000
max_concurrent_requests : 3

epi : fra-Latn-p
nlp : fr_core_news_lg

prompts : 
  system : services/system_prompt.txt
  user : services/user_prompt.txt
  normalisation : services/prompt_normalisation_v0.txt
  cri : services/cri_prompt.txt
  cra : services/cra_prompt.txt
  cred : services/cred_prompt.txt

placeholders : 
  redaction : rédaction de compte rendu
  correction : "la correction orthographique" 

container :
  - transcribe_empty
